dataset: 'california_housing'
task: 'regression'
resume_dir: 'housing'
logname: 'layer20'

fit:
  max_epochs: 2000
  patience: 500
  lr: 0.02

model:
  layer: 32
  base_outdim: 96
  k: 8
  drop_rate: 0.1